name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get price history
        run: |
          for symbol in `cat input/workspace.sym` 
          do 
            echo "Price history must be added manually for now."
            echo "Download 11 years of history using Yahoo's DOWNLOAD button"
            # Force download of just PSA history
            cd input ; wget https://query1.finance.yahoo.com/v7/finance/download/PSA?period1=1597606890&period2=1629142890&interval=1d&events=history&includeAdjustedClose=true
            ls -al
            #python scripts/get_price_history.py -s ${symbol}
            bash scripts/cycle_and_compare.sh -v -s PSA
          done
